filter:
  dependency_paths:
    - vendor/
    - vendors/
    - wordpress/
  excluded_paths:
    - assets/
    - languages/
    - node_modules/
    - tests/

build:
  nodes:
    analysis:
      cache:
        disabled: false
        directories:
          - ~/.composer/cache
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress
      environment:
        elasticsearch: false
        memcached: false
        mongodb: false
        neo4j: false
        node: '10.0.0'
        php: '7.4.0'
        postgresql: false
        rabbitmq: false
        redis: false
      project_setup:
        override: true
        before:
          - bash tests/bin/install.sh wordpress_test root "" localhost $WP_VERSION
          - bash tests/bin/travis.sh before
      tests:
        override:
          - jshint-run
          - php-scrutinizer-run --enable-security-analysis
          -
            command: vendor/bin/phpunit --coverage-clover=tests/coverage.xml
            coverage:
              file: tests/coverage.xml
              format: clover

tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true

checks:
  php:
    no_exit: false
    simplify_boolean_return: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
  javascript:
    no_else_return: true
    eqeqeq: true
