bump:
  - readme.txt
  - site-reviews.php
language:
  destination: languages/
  domain: site-reviews
  team: Gemini Labs <support@geminilabs.io>
  translator: Paul Ryley <paul@geminilabs.io>
  watch:
    - config/**/*.php
    - plugin/**/*.php
    - templates/**/*.php
    - views/**/*.php
    - '*.php'
